<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;

/**
 * Наши перевозчики (forwarder), наши экспедиторы (expeditor), третья сторона (carrier + is_third_party).
 * Латвия, Рига; третья сторона — произвольные названия (не из клиентов).
 */
class CarrierExpeditorCompaniesSeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            // --- 3 FORWARDER (наши перевозчики) ---
            [
                'slug'        => 'carrier-baltika',
                'name'        => 'SIA Baltika Trans',
                'type'        => 'forwarder',
                'is_broker'   => false,
                'is_third_party' => false,
                'reg_nr'      => '40103012345',
                'vat_nr'      => 'LV40103012345',
                'country'     => 'Latvija',
                'city'        => 'Rīga',
                'address'     => 'Dzirnavu iela 120, 4. stāvs',
                'post_code'   => 'LV-1012',
                'legal_country'   => 'Latvija',
                'legal_city'      => 'Rīga',
                'legal_address'   => 'Dzirnavu iela 120, 4. stāvs',
                'legal_post_code' => 'LV-1012',
                'physical_country'   => 'Latvija',
                'physical_city'      => 'Rīga',
                'physical_address'   => 'Dzirnavu iela 120, 4. stāvs',
                'physical_post_code' => 'LV-1012',
                'email'       => 'info@baltikatrans.lv',
                'phone'       => '+371 67012345',
                'banks_json'  => [
                    1 => [
                        'name' => 'Swedbank',
                        'iban' => 'LV12HABA0551234567890',
                        'bic'  => 'HABALV22',
                    ],
                ],
                'is_system'   => false,
                'is_active'   => true,
            ],
            [
                'slug'        => 'carrier-riga-freight',
                'name'        => 'SIA Rīga Freight',
                'type'        => 'forwarder',
                'is_broker'   => false,
                'is_third_party' => false,
                'reg_nr'      => '40203123456',
                'vat_nr'      => 'LV40203123456',
                'country'     => 'Latvija',
                'city'        => 'Rīga',
                'address'     => 'Krasta iela 46',
                'post_code'   => 'LV-1016',
                'legal_country'   => 'Latvija',
                'legal_city'      => 'Rīga',
                'legal_address'   => 'Krasta iela 46',
                'legal_post_code' => 'LV-1016',
                'physical_country'   => 'Latvija',
                'physical_city'      => 'Rīga',
                'physical_address'   => 'Krasta iela 46',
                'physical_post_code' => 'LV-1016',
                'email'       => 'office@rigafreight.lv',
                'phone'       => '+371 67890123',
                'banks_json'  => [
                    1 => [
                        'name' => 'SEB banka',
                        'iban' => 'LV44UNLA0051234567890',
                        'bic'  => 'UNLALV2X',
                    ],
                    2 => [
                        'name' => 'Citadele banka',
                        'iban' => 'LV09PARX0012345678901',
                        'bic'  => 'PARXLV22',
                    ],
                ],
                'is_system'   => false,
                'is_active'   => true,
            ],
            [
                'slug'        => 'carrier-latvijas-ceļš',
                'name'        => 'SIA Latvijas Ceļš',
                'type'        => 'forwarder',
                'is_broker'   => false,
                'is_third_party' => false,
                'reg_nr'      => '40303234567',
                'vat_nr'      => 'LV40303234567',
                'country'     => 'Latvija',
                'city'        => 'Rīga',
                'address'     => 'Ganību dambis 26',
                'post_code'   => 'LV-1005',
                'legal_country'   => 'Latvija',
                'legal_city'      => 'Rīga',
                'legal_address'   => 'Ganību dambis 26',
                'legal_post_code' => 'LV-1005',
                'physical_country'   => 'Latvija',
                'physical_city'      => 'Rīga',
                'physical_address'   => 'Ganību dambis 26',
                'physical_post_code' => 'LV-1005',
                'email'       => 'pavadzibas@latvijascelss.lv',
                'phone'       => '+371 29123456',
                'banks_json'  => [
                    1 => [
                        'name' => 'Luminor Bank',
                        'iban' => 'LV97HABA0551987654321',
                        'bic'  => 'HABALV22',
                    ],
                ],
                'is_system'   => false,
                'is_active'   => true,
            ],

            // --- 2 EXPEDITOR (наши экспедиторы) ---
            [
                'slug'        => 'expeditor-nord-cargo',
                'name'        => 'SIA Nord Cargo',
                'type'        => 'expeditor',
                'is_broker'   => false,
                'is_third_party' => false,
                'reg_nr'      => '40403345678',
                'vat_nr'      => 'LV40403345678',
                'country'     => 'Latvija',
                'city'        => 'Rīga',
                'address'     => 'Valdemāra iela 33',
                'post_code'   => 'LV-1010',
                'legal_country'   => 'Latvija',
                'legal_city'      => 'Rīga',
                'legal_address'   => 'Valdemāra iela 33',
                'legal_post_code' => 'LV-1010',
                'physical_country'   => 'Latvija',
                'physical_city'      => 'Rīga',
                'physical_address'   => 'Valdemāra iela 33',
                'physical_post_code' => 'LV-1010',
                'email'       => 'logistics@nordcargo.lv',
                'phone'       => '+371 26543210',
                'banks_json'  => [
                    1 => [
                        'name' => 'Swedbank',
                        'iban' => 'LV80HABA0551123456789',
                        'bic'  => 'HABALV22',
                    ],
                    2 => [
                        'name' => 'Revolut Bank',
                        'iban' => 'LT123500010012345678',
                        'bic'  => 'REVOLT21',
                    ],
                ],
                'is_system'   => false,
                'is_active'   => true,
            ],
            [
                'slug'        => 'expeditor-baltlog',
                'name'        => 'SIA Baltlog',
                'type'        => 'expeditor',
                'is_broker'   => false,
                'is_third_party' => false,
                'reg_nr'      => '40503456789',
                'vat_nr'      => 'LV40503456789',
                'country'     => 'Latvija',
                'city'        => 'Rīga',
                'address'     => 'Brīvības iela 98',
                'post_code'   => 'LV-1011',
                'legal_country'   => 'Latvija',
                'legal_city'      => 'Rīga',
                'legal_address'   => 'Brīvības iela 98',
                'legal_post_code' => 'LV-1011',
                'physical_country'   => 'Latvija',
                'physical_city'      => 'Rīga',
                'physical_address'   => 'Brīvības iela 98',
                'physical_post_code' => 'LV-1011',
                'email'       => 'info@baltlog.lv',
                'phone'       => '+371 27765432',
                'banks_json'  => [
                    1 => [
                        'name' => 'Citadele banka',
                        'iban' => 'LV72PARX0023456789012',
                        'bic'  => 'PARXLV22',
                    ],
                ],
                'is_system'   => false,
                'is_active'   => true,
            ],

            // --- 3 CARRIER третья сторона (для рейсов экспедиторов) ---
            [
                'slug'        => 'third-party-translitas',
                'name'        => 'UAB TransLitas',
                'type'        => 'carrier',
                'is_broker'   => false,
                'is_third_party' => true,
                'reg_nr'      => '30412345678',
                'vat_nr'      => 'LT100012345678',
                'country'     => 'Lietuva',
                'city'        => 'Vilnius',
                'address'     => 'Savanorių pr. 123',
                'post_code'   => 'LT-02300',
                'legal_country'   => 'Lietuva',
                'legal_city'      => 'Vilnius',
                'legal_address'   => 'Savanorių pr. 123',
                'legal_post_code' => 'LT-02300',
                'physical_country'   => 'Lietuva',
                'physical_city'      => 'Vilnius',
                'physical_address'   => 'Savanorių pr. 123',
                'physical_post_code' => 'LT-02300',
                'email'       => 'info@translitas.lt',
                'phone'       => '+370 612 34567',
                'banks_json'  => [],
                'is_system'   => false,
                'is_active'   => true,
            ],
            [
                'slug'        => 'third-party-eesti-vedu',
                'name'        => 'AS Eesti Vedu',
                'type'        => 'carrier',
                'is_broker'   => false,
                'is_third_party' => true,
                'reg_nr'      => '12345678',
                'vat_nr'      => 'EE10123456789',
                'country'     => 'Eesti',
                'city'        => 'Tallinn',
                'address'     => 'Pärnu mnt 100',
                'post_code'   => '10112',
                'legal_country'   => 'Eesti',
                'legal_city'      => 'Tallinn',
                'legal_address'   => 'Pärnu mnt 100',
                'legal_post_code' => '10112',
                'physical_country'   => 'Eesti',
                'physical_city'      => 'Tallinn',
                'physical_address'   => 'Pärnu mnt 100',
                'physical_post_code' => '10112',
                'email'       => 'logistics@eestivedu.ee',
                'phone'       => '+372 612 3456',
                'banks_json'  => [],
                'is_system'   => false,
                'is_active'   => true,
            ],
            [
                'slug'        => 'third-party-poland-freight',
                'name'        => 'TransPol Sp. z o.o.',
                'type'        => 'carrier',
                'is_broker'   => false,
                'is_third_party' => true,
                'reg_nr'      => '0000123456',
                'vat_nr'      => 'PL1234567890',
                'country'     => 'Polska',
                'city'        => 'Warszawa',
                'address'     => 'ul. Logistyczna 5',
                'post_code'   => '02-123',
                'legal_country'   => 'Polska',
                'legal_city'      => 'Warszawa',
                'legal_address'   => 'ul. Logistyczna 5',
                'legal_post_code' => '02-123',
                'physical_country'   => 'Polska',
                'physical_city'      => 'Warszawa',
                'physical_address'   => 'ul. Logistyczna 5',
                'physical_post_code' => '02-123',
                'email'       => 'biuro@transpol.pl',
                'phone'       => '+48 22 123 45 67',
                'banks_json'  => [],
                'is_system'   => false,
                'is_active'   => true,
            ],
        ];

        foreach ($companies as $data) {
            Company::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
