<?php

return [
    1 => ['name' => 'Dubai', 'region' => 'Dubai'],
    2 => ['name' => 'Abu Dhabi'],
    3 => ['name' => 'Sharjah'],
    4 => ['name' => 'Ajman'],
    5 => ['name' => 'Ras Al Khaimah'],
    6 => ['name' => 'Fujairah'],
    7 => ['name' => 'Umm Al Quwain'],
    8 => ['name' => 'Al Ain'],
    9 => ['name' => 'Khalifa City'],
    10 => ['name' => 'Mussafah'],
    11 => ['name' => 'Bani Yas'],
    12 => ['name' => 'Al Shamkha'],
    13 => ['name' => 'Madinat Zayed'],
    14 => ['name' => 'Liwa'],
    15 => ['name' => 'Ruwais'],
    16 => ['name' => 'Ghayathi'],
    17 => ['name' => 'Delma Island'],
    18 => ['name' => 'Al Dhafra'],
    19 => ['name' => 'Jebel Ali'],
    20 => ['name' => 'Deira'],
    21 => ['name' => 'Bur Dubai'],
    22 => ['name' => 'Jumeirah'],
    23 => ['name' => 'Al Barsha'],
    24 => ['name' => 'Al Nahda'],
    25 => ['name' => 'Al Qusais'],
    26 => ['name' => 'Al Karama'],
    27 => ['name' => 'Mirdif'],
    28 => ['name' => 'Al Warqa'],
    29 => ['name' => 'Dubai Marina'],
    30 => ['name' => 'Palm Jumeirah'],
    31 => ['name' => 'Business Bay'],
    32 => ['name' => 'Al Satwa'],
    33 => ['name' => 'Al Quoz'],
    34 => ['name' => 'Al Khail Heights'],
    35 => ['name' => 'DIFC'],
    36 => ['name' => 'Al Majaz'],
    37 => ['name' => 'Al Khan'],
    38 => ['name' => 'Muwaileh'],
    39 => ['name' => 'University City'],
    40 => ['name' => 'Al Dhaid'],
    41 => ['name' => 'Khor Fakkan'],
    42 => ['name' => 'Dibba Al Fujairah'],
    43 => ['name' => 'Dibba Al Hisn'],
    44 => ['name' => 'Masafi'],
    45 => ['name' => 'Hatta'],
    46 => ['name' => 'Al Jazirah Al Hamra'],
    47 => ['name' => 'Digdaga'],
    48 => ['name' => 'Ghalilah'],
    49 => ['name' => 'Al Hamra Village'],
    50 => ['name' => 'Al Nakheel'],
    51 => ['name' => 'Al Marjan Island'],
    52 => ['name' => 'Al Taawun'],
    53 => ['name' => 'Al Qurm'],
    54 => ['name' => 'Al Nahda Sharjah'],
    55 => ['name' => 'Al Majaz Sharjah'],
    56 => ['name' => 'Al Khan Sharjah'],
    57 => ['name' => 'Al Batayeh'],
    58 => ['name' => 'Al Zubair'],
    59 => ['name' => 'Al Heerah'],
    60 => ['name' => 'Al Badiyah'],
];
