<?php

return [
    1 => ['name' => 'Vienna'],
    2 => ['name' => 'Graz'],
    3 => ['name' => 'Linz'],
    4 => ['name' => 'Salzburg'],
    5 => ['name' => 'Innsbruck'],
    6 => ['name' => 'Klagenfurt'],
    7 => ['name' => 'Villach'],
    8 => ['name' => 'Wels'],
    9 => ['name' => 'Sankt Pölten'],
    10 => ['name' => 'Dornbirn'],
    11 => ['name' => 'Wiener Neustadt'],
    12 => ['name' => 'Steyr'],
    13 => ['name' => 'Feldkirch'],
    14 => ['name' => 'Bregenz'],
    15 => ['name' => 'Leonding'],
    16 => ['name' => 'Klosterneuburg'],
    17 => ['name' => 'Baden bei Wien'],
    18 => ['name' => 'Wolfsberg'],
    19 => ['name' => 'Leoben'],
    20 => ['name' => 'Krems an der Donau'],
    21 => ['name' => 'Traun'],
    22 => ['name' => 'Amstetten'],
    23 => ['name' => 'Lustenau'],
    24 => ['name' => 'Kapfenberg'],
    25 => ['name' => 'Mödling'],
    26 => ['name' => 'Hallein'],
    27 => ['name' => 'Kufstein'],
    28 => ['name' => 'Schwechat'],
    29 => ['name' => 'Braunau am Inn'],
    30 => ['name' => 'Stockerau'],
    31 => ['name' => 'Saalfelden'],
    32 => ['name' => 'Ansfelden'],
    33 => ['name' => 'Tulln'],
    34 => ['name' => 'Hohenems'],
    35 => ['name' => 'Spittal an der Drau'],
    36 => ['name' => 'Ternitz'],
    37 => ['name' => 'Perchtoldsdorf'],
    38 => ['name' => 'Feldkirchen'],
    39 => ['name' => 'Bludenz'],
    40 => ['name' => 'Bad Ischl'],
    41 => ['name' => 'Eisenstadt'],
    42 => ['name' => 'Gmunden'],
    43 => ['name' => 'Bruck an der Mur'],
    44 => ['name' => 'Sankt Veit an der Glan'],
    45 => ['name' => 'Zwettl'],
    46 => ['name' => 'Vöcklabruck'],
    47 => ['name' => 'Waidhofen an der Ybbs'],
    48 => ['name' => 'Knittelfeld'],
    49 => ['name' => 'Lienz'],
    50 => ['name' => 'Villach'],
    51 => ['name' => 'Ried im Innkreis'],
    52 => ['name' => 'Schwaz'],
    53 => ['name' => 'Kitzbühel'],
    54 => ['name' => 'Lienz'],
    55 => ['name' => 'Judenburg'],
    56 => ['name' => 'Deutschlandsberg'],
    57 => ['name' => 'Hartberg'],
    58 => ['name' => 'Güssing'],
    59 => ['name' => 'Oberwart'],
    60 => ['name' => 'Mattersburg'],
];
