<?php

return [
    1 => ['name' => 'Sofia'],
    2 => ['name' => 'Plovdiv'],
    3 => ['name' => 'Varna'],
    4 => ['name' => 'Burgas'],
    5 => ['name' => 'Ruse'],
    6 => ['name' => 'Stara Zagora'],
    7 => ['name' => 'Pleven'],
    8 => ['name' => 'Sliven'],
    9 => ['name' => 'Dobrich'],
    10 => ['name' => 'Shumen'],
    11 => ['name' => 'Pernik'],
    12 => ['name' => 'Haskovo'],
    13 => ['name' => 'Yambol'],
    14 => ['name' => 'Pazardzhik'],
    15 => ['name' => 'Blagoevgrad'],
    16 => ['name' => 'Veliko Tarnovo'],
    17 => ['name' => 'Vratsa'],
    18 => ['name' => 'Gabrovo'],
    19 => ['name' => 'Asenovgrad'],
    20 => ['name' => 'Vidin'],
    21 => ['name' => 'Kazanlak'],
    22 => ['name' => 'Kyustendil'],
    23 => ['name' => 'Montana'],
    24 => ['name' => 'Dimitrovgrad'],
    25 => ['name' => 'Targovishte'],
    26 => ['name' => 'Lovech'],
    27 => ['name' => 'Silistra'],
    28 => ['name' => 'Razgrad'],
    29 => ['name' => 'Gorna Oryahovitsa'],
    30 => ['name' => 'Smolyan'],
    31 => ['name' => 'Petrich'],
    32 => ['name' => 'Sandanski'],
    33 => ['name' => 'Samokov'],
    34 => ['name' => 'Lom'],
    35 => ['name' => 'Dupnitsa'],
    36 => ['name' => 'Svishtov'],
    37 => ['name' => 'Nova Zagora'],
    38 => ['name' => 'Sevlievo'],
    39 => ['name' => 'Troyan'],
    40 => ['name' => 'Aytos'],
    41 => ['name' => 'Botevgrad'],
    42 => ['name' => 'Gotse Delchev'],
    43 => ['name' => 'Karlovo'],
    44 => ['name' => 'Panagyurishte'],
    45 => ['name' => 'Svilengrad'],
    46 => ['name' => 'Harmanli'],
    47 => ['name' => 'Radnevo'],
    48 => ['name' => 'Peshtera'],
    49 => ['name' => 'Chirpan'],
    50 => ['name' => 'Popovo'],
    51 => ['name' => 'Rakovski'],
    52 => ['name' => 'Novi Iskar'],
    53 => ['name' => 'Byala Slatina'],
    54 => ['name' => 'Pomorie'],
    55 => ['name' => 'Nesebar'],
    56 => ['name' => 'Radomir'],
    57 => ['name' => 'Kozloduy'],
    58 => ['name' => 'Berkovitsa'],
    59 => ['name' => 'Pirdop'],
    60 => ['name' => 'Karnobat'],
];
