<?php

return [
    1 => ['name' => 'Minsk', 'region' => 'Minsk'],
    2 => ['name' => 'Gomel'],
    3 => ['name' => 'Mogilev'],
    4 => ['name' => 'Vitebsk'],
    5 => ['name' => 'Grodno'],
    6 => ['name' => 'Brest'],
    7 => ['name' => 'Bobruisk'],
    8 => ['name' => 'Baranavichy'],
    9 => ['name' => 'Barysau'],
    10 => ['name' => 'Pinsk'],
    11 => ['name' => 'Orsha'],
    12 => ['name' => 'Mazyr'],
    13 => ['name' => 'Salihorsk'],
    14 => ['name' => 'Novopolotsk'],
    15 => ['name' => 'Lida'],
    16 => ['name' => 'Maladzyechna'],
    17 => ['name' => 'Polatsk'],
    18 => ['name' => 'Zhlobin'],
    19 => ['name' => 'Svetlahorsk'],
    20 => ['name' => 'Rechytsa'],
    21 => ['name' => 'Slutsk'],
    22 => ['name' => 'Zhodzina'],
    23 => ['name' => 'Slonim'],
    24 => ['name' => 'Kobryn'],
    25 => ['name' => 'Vawkavysk'],
    26 => ['name' => 'Kalinkavichy'],
    27 => ['name' => 'Smarhon'],
    28 => ['name' => 'Rahachow'],
    29 => ['name' => 'Asipovichy'],
    30 => ['name' => 'Horki'],
    31 => ['name' => 'Navahrudak'],
    32 => ['name' => 'Vilyeyka'],
    33 => ['name' => 'Byaroza'],
    34 => ['name' => 'Krychaw'],
    35 => ['name' => 'Dzyarzhynsk'],
    36 => ['name' => 'Ivanava'],
    37 => ['name' => 'Dobrush'],
    38 => ['name' => 'Hlybokaye'],
    39 => ['name' => 'Luninyets'],
    40 => ['name' => 'Pastavy'],
    41 => ['name' => 'Stolin'],
    42 => ['name' => 'Lyepyel'],
    43 => ['name' => 'Marina Horka'],
    44 => ['name' => 'Klimavichy'],
    45 => ['name' => 'Kastsyukovichy'],
    46 => ['name' => 'Buda-Kashalyova'],
    47 => ['name' => 'Bykhaw'],
    48 => ['name' => 'Homyel'],
    49 => ['name' => 'Chavusy'],
    50 => ['name' => 'Talachyn'],
    51 => ['name' => 'Braslaw'],
    52 => ['name' => 'Shklow'],
    53 => ['name' => 'Krupki'],
    54 => ['name' => 'Uzda'],
    55 => ['name' => 'Drahichyn'],
    56 => ['name' => 'Klichaw'],
    57 => ['name' => 'Masty'],
    58 => ['name' => 'Vetka'],
    59 => ['name' => 'Chachersk'],
    60 => ['name' => 'Turau'],
];
