<?php

return [
    1 => ['name' => 'Nicosia'],
    2 => ['name' => 'Limassol'],
    3 => ['name' => 'Larnaca'],
    4 => ['name' => 'Paphos'],
    5 => ['name' => 'Famagusta'],
    6 => ['name' => 'Kyrenia'],
    7 => ['name' => 'Protaras'],
    8 => ['name' => 'Ayia Napa'],
    9 => ['name' => 'Morphou'],
    10 => ['name' => 'Larnaca District'],
    11 => ['name' => 'Paralimni'],
    12 => ['name' => 'Lefkara'],
    13 => ['name' => 'Polis'],
    14 => ['name' => 'Pissouri'],
    15 => ['name' => 'Peyia'],
    16 => ['name' => 'Pergamos'],
    17 => ['name' => 'Aradippou'],
    18 => ['name' => 'Livadia'],
    19 => ['name' => 'Dromolaxia'],
    20 => ['name' => 'Mesa Geitonia'],
    21 => ['name' => 'Agios Athanasios'],
    22 => ['name' => 'Germasogeia'],
    23 => ['name' => 'Ypsonas'],
    24 => ['name' => 'Kato Polemidia'],
    25 => ['name' => 'Strovolos'],
    26 => ['name' => 'Lakatamia'],
    27 => ['name' => 'Engomi'],
    28 => ['name' => 'Aglandjia'],
    29 => ['name' => 'Mesa Geitonia'],
    30 => ['name' => 'Tseri'],
    31 => ['name' => 'Dali'],
    32 => ['name' => 'Latsia'],
    33 => ['name' => 'Pano Polemidia'],
    34 => ['name' => 'Kiti'],
    35 => ['name' => 'Xylofagou'],
    36 => ['name' => 'Avgorou'],
    37 => ['name' => 'Sotira'],
    38 => ['name' => 'Frenaros'],
    39 => ['name' => 'Liopetri'],
    40 => ['name' => 'Athienou'],
    41 => ['name' => 'Kofinou'],
    42 => ['name' => 'Zyyi'],
    43 => ['name' => 'Agios Tychonas'],
    44 => ['name' => 'Kolossi'],
    45 => ['name' => 'Episkopi'],
    46 => ['name' => 'Akrotiri'],
    47 => ['name' => 'Pissouri'],
    48 => ['name' => 'Kouklia'],
    49 => ['name' => 'Emba'],
    50 => ['name' => 'Tala'],
    51 => ['name' => 'Chlorakas'],
    52 => ['name' => 'Geroskipou'],
    53 => ['name' => 'Mesogi'],
    54 => ['name' => 'Tsada'],
    55 => ['name' => 'Kathikas'],
    56 => ['name' => 'Pano Akourdalia'],
    57 => ['name' => 'Fyti'],
    58 => ['name' => 'Lysos'],
    59 => ['name' => 'Pomos'],
    60 => ['name' => 'Pyrgos'],
];
