<?php

return [
    1 => ['name' => 'Prague'],
    2 => ['name' => 'Brno'],
    3 => ['name' => 'Ostrava'],
    4 => ['name' => 'Pilsen'],
    5 => ['name' => 'Liberec'],
    6 => ['name' => 'Olomouc'],
    7 => ['name' => 'České Budějovice'],
    8 => ['name' => 'Hradec Králové'],
    9 => ['name' => 'Ústí nad Labem'],
    10 => ['name' => 'Pardubice'],
    11 => ['name' => 'Zlín'],
    12 => ['name' => 'Havířov'],
    13 => ['name' => 'Kladno'],
    14 => ['name' => 'Most'],
    15 => ['name' => 'Opava'],
    16 => ['name' => 'Frýdek-Místek'],
    17 => ['name' => 'Karviná'],
    18 => ['name' => 'Jihlava'],
    19 => ['name' => 'Teplice'],
    20 => ['name' => 'Chomutov'],
    21 => ['name' => 'Jablonec nad Nisou'],
    22 => ['name' => 'Prostějov'],
    23 => ['name' => 'Mladá Boleslav'],
    24 => ['name' => 'Česká Lípa'],
    25 => ['name' => 'Třebíč'],
    26 => ['name' => 'Trutnov'],
    27 => ['name' => 'Znojmo'],
    28 => ['name' => 'Přerov'],
    29 => ['name' => 'Cheb'],
    30 => ['name' => 'Kolín'],
    31 => ['name' => 'Kroměříž'],
    32 => ['name' => 'Šumperk'],
    33 => ['name' => 'Vsetín'],
    34 => ['name' => 'Litoměřice'],
    35 => ['name' => 'Nový Jičín'],
    36 => ['name' => 'Uherské Hradiště'],
    37 => ['name' => 'Hodonín'],
    38 => ['name' => 'Břeclav'],
    39 => ['name' => 'Žďár nad Sázavou'],
    40 => ['name' => 'Blansko'],
    41 => ['name' => 'Sokolov'],
    42 => ['name' => 'Kladno'],
    43 => ['name' => 'Litvinov'],
    44 => ['name' => 'Valašské Meziříčí'],
    45 => ['name' => 'Chrudim'],
    46 => ['name' => 'Havlíčkův Brod'],
    47 => ['name' => 'Kopřivnice'],
    48 => ['name' => 'Kutná Hora'],
    49 => ['name' => 'Kyjov'],
    50 => ['name' => 'Náchod'],
    51 => ['name' => 'Jindřichův Hradec'],
    52 => ['name' => 'Děčín'],
    53 => ['name' => 'Varnsdorf'],
    54 => ['name' => 'Orlová'],
    55 => ['name' => 'Beroun'],
    56 => ['name' => 'Tábor'],
    57 => ['name' => 'Pelhřimov'],
    58 => ['name' => 'Tachov'],
    59 => ['name' => 'Svitavy'],
    60 => ['name' => 'Žamberk'],
];
