<?php

return [
    1  => ['name' => 'Berlin'],
    2  => ['name' => 'Hamburg'],
    3  => ['name' => 'München'],
    4  => ['name' => 'Köln'],
    5  => ['name' => 'Frankfurt am Main'],
    6  => ['name' => 'Stuttgart'],
    7  => ['name' => 'Düsseldorf'],
    8  => ['name' => 'Dortmund'],
    9  => ['name' => 'Essen'],
    10 => ['name' => 'Leipzig'],
    11 => ['name' => 'Bremen'],
    12 => ['name' => 'Dresden'],
    13 => ['name' => 'Hannover'],
    14 => ['name' => 'Nürnberg'],
    15 => ['name' => 'Duisburg'],
    16 => ['name' => 'Bochum'],
    17 => ['name' => 'Wuppertal'],
    18 => ['name' => 'Bielefeld'],
    19 => ['name' => 'Bonn'],
    20 => ['name' => 'Münster'],
    21 => ['name' => 'Karlsruhe'],
    22 => ['name' => 'Mannheim'],
    23 => ['name' => 'Augsburg'],
    24 => ['name' => 'Wiesbaden'],
    25 => ['name' => 'Gelsenkirchen'],
    26 => ['name' => 'Mönchengladbach'],
    27 => ['name' => 'Braunschweig'],
    28 => ['name' => 'Chemnitz'],
    29 => ['name' => 'Kiel'],
    30 => ['name' => 'Aachen'],
    31 => ['name' => 'Halle'],
    32 => ['name' => 'Magdeburg'],
    33 => ['name' => 'Freiburg im Breisgau'],
    34 => ['name' => 'Krefeld'],
    35 => ['name' => 'Lübeck'],
    36 => ['name' => 'Oberhausen'],
    37 => ['name' => 'Erfurt'],
    38 => ['name' => 'Hagen'],
    39 => ['name' => 'Kassel'],
    40 => ['name' => 'Hamm'],
    41 => ['name' => 'Mainz'],
    42 => ['name' => 'Saarbrücken'],
    43 => ['name' => 'Rostock'],
    44 => ['name' => 'Leverkusen'],
    45 => ['name' => 'Oldenburg'],
    46 => ['name' => 'Ludwigshafen'],
    47 => ['name' => 'Osnabrück'],
    48 => ['name' => 'Solingen'],
    49 => ['name' => 'Heidelberg'],
    50 => ['name' => 'Herne'],
    51 => ['name' => 'Neuss'],
    52 => ['name' => 'Darmstadt'],
    53 => ['name' => 'Paderborn'],
    54 => ['name' => 'Regensburg'],
    55 => ['name' => 'Ingolstadt'],
    56 => ['name' => 'Würzburg'],
    57 => ['name' => 'Wolfsburg'],
    58 => ['name' => 'Ulm'],
    59 => ['name' => 'Heilbronn'],
    60 => ['name' => 'Pforzheim'],
];
