<?php

return [
    1 => ['name' => 'Copenhagen'],
    2 => ['name' => 'Aarhus'],
    3 => ['name' => 'Odense'],
    4 => ['name' => 'Aalborg'],
    5 => ['name' => 'Frederiksberg'],
    6 => ['name' => 'Esbjerg'],
    7 => ['name' => 'Gentofte'],
    8 => ['name' => 'Gladsaxe'],
    9 => ['name' => 'Randers'],
    10 => ['name' => 'Kolding'],
    11 => ['name' => 'Horsens'],
    12 => ['name' => 'Vejle'],
    13 => ['name' => 'Roskilde'],
    14 => ['name' => 'Herning'],
    15 => ['name' => 'Hørsholm'],
    16 => ['name' => 'Helsingør'],
    17 => ['name' => 'Silkeborg'],
    18 => ['name' => 'Næstved'],
    19 => ['name' => 'Fredericia'],
    20 => ['name' => 'Køge'],
    21 => ['name' => 'Viborg'],
    22 => ['name' => 'Holstebro'],
    23 => ['name' => 'Taastrup'],
    24 => ['name' => 'Slagelse'],
    25 => ['name' => 'Hillærød'],
    26 => ['name' => 'Holbæk'],
    27 => ['name' => 'Svendborg'],
    28 => ['name' => 'Sønderborg'],
    29 => ['name' => 'Hjørring'],
    30 => ['name' => 'Frederikshavn'],
    31 => ['name' => 'Glostrup'],
    32 => ['name' => 'Hvidovre'],
    33 => ['name' => 'Charlottenlund'],
    34 => ['name' => 'Ballerup'],
    35 => ['name' => 'Rødovre'],
    36 => ['name' => 'Helsingør'],
    37 => ['name' => 'Haderslev'],
    38 => ['name' => 'Skive'],
    39 => ['name' => 'Skagen'],
    40 => ['name' => 'Thisted'],
    41 => ['name' => 'Nykøbing Falster'],
    42 => ['name' => 'Ringsted'],
    43 => ['name' => 'Hobro'],
    44 => ['name' => 'Korsør'],
    45 => ['name' => 'Varde'],
    46 => ['name' => 'Struer'],
    47 => ['name' => 'Nakskov'],
    48 => ['name' => 'Middelfart'],
    49 => ['name' => 'Nyborg'],
    50 => ['name' => 'Skanderborg'],
    51 => ['name' => 'Kalundborg'],
    52 => ['name' => 'Nykøbing Mors'],
    53 => ['name' => 'Lillerød'],
    54 => ['name' => 'Rønne'],
    55 => ['name' => 'Mariager'],
    56 => ['name' => 'Ebeltoft'],
    57 => ['name' => 'Helsingør'],
    58 => ['name' => 'Grenaa'],
    59 => ['name' => 'Faaborg'],
    60 => ['name' => 'Assens'],
];
