<?php

return [
    1 => ['name' => 'Madrid'],
    2 => ['name' => 'Barcelona'],
    3 => ['name' => 'Valencia'],
    4 => ['name' => 'Seville'],
    5 => ['name' => 'Zaragoza'],
    6 => ['name' => 'Málaga'],
    7 => ['name' => 'Murcia'],
    8 => ['name' => 'Palma de Mallorca'],
    9 => ['name' => 'Las Palmas'],
    10 => ['name' => 'Bilbao'],
    11 => ['name' => 'Alicante'],
    12 => ['name' => 'Córdoba'],
    13 => ['name' => 'Valladolid'],
    14 => ['name' => 'Vigo'],
    15 => ['name' => 'Gijón'],
    16 => ['name' => 'Hospitalet de Llobregat'],
    17 => ['name' => 'Vitoria-Gasteiz'],
    18 => ['name' => 'Granada'],
    19 => ['name' => 'Elche'],
    20 => ['name' => 'Oviedo'],
    21 => ['name' => 'Badalona'],
    22 => ['name' => 'Cartagena'],
    23 => ['name' => 'Terrassa'],
    24 => ['name' => 'Sabadell'],
    25 => ['name' => 'Santa Cruz de Tenerife'],
    26 => ['name' => 'Pamplona'],
    27 => ['name' => 'Santander'],
    28 => ['name' => 'León'],
    29 => ['name' => 'Tarragona'],
    30 => ['name' => 'Castellón de la Plana'],
    31 => ['name' => 'Burgos'],
    32 => ['name' => 'Salamanca'],
    33 => ['name' => 'Logroño'],
    34 => ['name' => 'Cádiz'],
    35 => ['name' => 'San Sebastián'],
    36 => ['name' => 'Albacete'],
    37 => ['name' => 'Getafe'],
    38 => ['name' => 'Fuenlabrada'],
    39 => ['name' => 'Almería'],
    40 => ['name' => 'Huelva'],
    41 => ['name' => 'Lleida'],
    42 => ['name' => 'Badajoz'],
    43 => ['name' => 'Toledo'],
    44 => ['name' => 'Girona'],
    45 => ['name' => 'Lugo'],
    46 => ['name' => 'Ourense'],
    47 => ['name' => 'Pontevedra'],
    48 => ['name' => 'Santander'],
    49 => ['name' => 'Jaén'],
    50 => ['name' => 'Algeciras'],
    51 => ['name' => 'Marbella'],
    52 => ['name' => 'Torrevieja'],
    53 => ['name' => 'Santiago de Compostela'],
    54 => ['name' => 'Cáceres'],
    55 => ['name' => 'Ceuta'],
    56 => ['name' => 'Melilla'],
    57 => ['name' => 'Lorca'],
    58 => ['name' => 'Sagunto'],
    59 => ['name' => 'Gandia'],
    60 => ['name' => 'Reus'],
];
