<?php

return [
    1 => ['name' => 'Paris'],
    2 => ['name' => 'Marseille'],
    3 => ['name' => 'Lyon'],
    4 => ['name' => 'Toulouse'],
    5 => ['name' => 'Nice'],
    6 => ['name' => 'Nantes'],
    7 => ['name' => 'Strasbourg'],
    8 => ['name' => 'Montpellier'],
    9 => ['name' => 'Bordeaux'],
    10 => ['name' => 'Lille'],
    11 => ['name' => 'Rennes'],
    12 => ['name' => 'Reims'],
    13 => ['name' => 'Saint-Étienne'],
    14 => ['name' => 'Toulon'],
    15 => ['name' => 'Le Havre'],
    16 => ['name' => 'Grenoble'],
    17 => ['name' => 'Dijon'],
    18 => ['name' => 'Angers'],
    19 => ['name' => 'Nîmes'],
    20 => ['name' => 'Villeurbanne'],
    21 => ['name' => 'Le Mans'],
    22 => ['name' => 'Aix-en-Provence'],
    23 => ['name' => 'Clermont-Ferrand'],
    24 => ['name' => 'Brest'],
    25 => ['name' => 'Tours'],
    26 => ['name' => 'Amiens'],
    27 => ['name' => 'Limoges'],
    28 => ['name' => 'Annecy'],
    29 => ['name' => 'Perpignan'],
    30 => ['name' => 'Béziers'],
    31 => ['name' => 'Metz'],
    32 => ['name' => 'Besançon'],
    33 => ['name' => 'Orléans'],
    34 => ['name' => 'Rouen'],
    35 => ['name' => 'Mulhouse'],
    36 => ['name' => 'Caen'],
    37 => ['name' => 'Nancy'],
    38 => ['name' => 'Saint-Denis'],
    39 => ['name' => 'Argenteuil'],
    40 => ['name' => 'Montreuil'],
    41 => ['name' => 'Saint-Paul'],
    42 => ['name' => 'Avignon'],
    43 => ['name' => 'Poitiers'],
    44 => ['name' => 'Versailles'],
    45 => ['name' => 'Créteil'],
    46 => ['name' => 'Pau'],
    47 => ['name' => 'Colombes'],
    48 => ['name' => 'La Rochelle'],
    49 => ['name' => 'Champigny-sur-Marne'],
    50 => ['name' => 'Rueil-Malmaison'],
    51 => ['name' => 'Fort-de-France'],
    52 => ['name' => 'Saint-Maur-des-Fossés'],
    53 => ['name' => 'Cannes'],
    54 => ['name' => 'Calais'],
    55 => ['name' => 'Dunkerque'],
    56 => ['name' => 'Bourges'],
    57 => ['name' => 'Troyes'],
    58 => ['name' => 'Antibes'],
    59 => ['name' => 'Lorient'],
    60 => ['name' => 'Bayonne'],
];
