<?php

return [
    1 => ['name' => 'Zagreb'],
    2 => ['name' => 'Split'],
    3 => ['name' => 'Rijeka'],
    4 => ['name' => 'Osijek'],
    5 => ['name' => 'Zadar'],
    6 => ['name' => 'Pula'],
    7 => ['name' => 'Slavonski Brod'],
    8 => ['name' => 'Karlovac'],
    9 => ['name' => 'Varaždin'],
    10 => ['name' => 'Šibenik'],
    11 => ['name' => 'Sisak'],
    12 => ['name' => 'Vinkovci'],
    13 => ['name' => 'Vukovar'],
    14 => ['name' => 'Dubrovnik'],
    15 => ['name' => 'Bjelovar'],
    16 => ['name' => 'Koprivnica'],
    17 => ['name' => 'Đakovo'],
    18 => ['name' => 'Požega'],
    19 => ['name' => 'Zaprešić'],
    20 => ['name' => 'Solin'],
    21 => ['name' => 'Kaštela'],
    22 => ['name' => 'Samobor'],
    23 => ['name' => 'Virovitica'],
    24 => ['name' => 'Kutina'],
    25 => ['name' => 'Crikvenica'],
    26 => ['name' => 'Makarska'],
    27 => ['name' => 'Sinj'],
    28 => ['name' => 'Petrinja'],
    29 => ['name' => 'Krapina'],
    30 => ['name' => 'Đurđevac'],
    31 => ['name' => 'Metković'],
    32 => ['name' => 'Poreč'],
    33 => ['name' => 'Našice'],
    34 => ['name' => 'Novi Marof'],
    35 => ['name' => 'Jastrebarsko'],
    36 => ['name' => 'Knin'],
    37 => ['name' => 'Slatina'],
    38 => ['name' => 'Omiš'],
    39 => ['name' => 'Ivanić-Grad'],
    40 => ['name' => 'Vrbovec'],
    41 => ['name' => 'Nova Gradiška'],
    42 => ['name' => 'Ogulin'],
    43 => ['name' => 'Pleternica'],
    44 => ['name' => 'Daruvar'],
    45 => ['name' => 'Čakovec'],
    46 => ['name' => 'Valpovo'],
    47 => ['name' => 'Križevci'],
    48 => ['name' => 'Imotski'],
    49 => ['name' => 'Gospić'],
    50 => ['name' => 'Benkovac'],
    51 => ['name' => 'Trilj'],
    52 => ['name' => 'Labin'],
    53 => ['name' => 'Opatija'],
    54 => ['name' => 'Rovinj'],
    55 => ['name' => 'Umag'],
    56 => ['name' => 'Pazin'],
    57 => ['name' => 'Buzet'],
    58 => ['name' => 'Belišće'],
    59 => ['name' => 'Duga Resa'],
    60 => ['name' => 'Vodice'],
];
