<?php

return [
    1 => ['name' => 'Rome'],
    2 => ['name' => 'Milan'],
    3 => ['name' => 'Naples'],
    4 => ['name' => 'Turin'],
    5 => ['name' => 'Palermo'],
    6 => ['name' => 'Genoa'],
    7 => ['name' => 'Bologna'],
    8 => ['name' => 'Florence'],
    9 => ['name' => 'Venice'],
    10 => ['name' => 'Verona'],
    11 => ['name' => 'Messina'],
    12 => ['name' => 'Padua'],
    13 => ['name' => 'Trieste'],
    14 => ['name' => 'Brescia'],
    15 => ['name' => 'Parma'],
    16 => ['name' => 'Modena'],
    17 => ['name' => 'Prato'],
    18 => ['name' => 'Reggio Calabria'],
    19 => ['name' => 'Livorno'],
    20 => ['name' => 'Cagliari'],
    21 => ['name' => 'Foggia'],
    22 => ['name' => 'Ravenna'],
    23 => ['name' => 'Ferrara'],
    24 => ['name' => 'Syracuse'],
    25 => ['name' => 'Sassari'],
    26 => ['name' => 'Latina'],
    27 => ['name' => 'Giugliano in Campania'],
    28 => ['name' => 'Monza'],
    29 => ['name' => 'Bergamo'],
    30 => ['name' => 'Pescara'],
    31 => ['name' => 'Trento'],
    32 => ['name' => 'Vicenza'],
    33 => ['name' => 'Bolzano'],
    34 => ['name' => 'Udine'],
    35 => ['name' => 'Arezzo'],
    36 => ['name' => 'Cesena'],
    37 => ['name' => 'Lecce'],
    38 => ['name' => 'Barletta'],
    39 => ['name' => 'Piacenza'],
    40 => ['name' => 'Novara'],
    41 => ['name' => 'Andria'],
    42 => ['name' => 'Altamura'],
    43 => ['name' => 'Busto Arsizio'],
    44 => ['name' => 'Brescia'],
    45 => ['name' => 'Catanzaro'],
    46 => ['name' => 'Savona'],
    47 => ['name' => 'Rimini'],
    48 => ['name' => 'Sanremo'],
    49 => ['name' => 'Lucca'],
    50 => ['name' => 'Pisa'],
    51 => ['name' => 'Siena'],
    52 => ['name' => 'Perugia'],
    53 => ['name' => 'Ancona'],
    54 => ['name' => 'Ascoli Piceno'],
    55 => ['name' => 'Frosinone'],
    56 => ['name' => 'Caserta'],
    57 => ['name' => 'Salerno'],
    58 => ['name' => 'Benevento'],
    59 => ['name' => 'Taranto'],
    60 => ['name' => 'Brindisi'],
];
