<?php

return [
    1 => ['name' => 'Chișinău'],
    2 => ['name' => 'Tiraspol'],
    3 => ['name' => 'Bălți'],
    4 => ['name' => 'Bender'],
    5 => ['name' => 'Cahul'],
    6 => ['name' => 'Ungheni'],
    7 => ['name' => 'Soroca'],
    8 => ['name' => 'Orhei'],
    9 => ['name' => 'Dubăsari'],
    10 => ['name' => 'Comrat'],
    11 => ['name' => 'Căușeni'],
    12 => ['name' => 'Strășeni'],
    13 => ['name' => 'Florești'],
    14 => ['name' => 'Drochia'],
    15 => ['name' => 'Slobozia'],
    16 => ['name' => 'Rîbnița'],
    17 => ['name' => 'Edineț'],
    18 => ['name' => 'Briceni'],
    19 => ['name' => 'Ocnița'],
    20 => ['name' => 'Dondușeni'],
    21 => ['name' => 'Glodeni'],
    22 => ['name' => 'Fălești'],
    23 => ['name' => 'Sângerei'],
    24 => ['name' => 'Telenești'],
    25 => ['name' => 'Rezina'],
    26 => ['name' => 'Orhei'],
    27 => ['name' => 'Călărași'],
    28 => ['name' => 'Nisporeni'],
    29 => ['name' => 'Hîncești'],
    30 => ['name' => 'Leova'],
    31 => ['name' => 'Cantemir'],
    32 => ['name' => 'Taraclia'],
    33 => ['name' => 'Basarabeasca'],
    34 => ['name' => 'Cimișlia'],
    35 => ['name' => 'Ștefan Vodă'],
    36 => ['name' => 'Anenii Noi'],
    37 => ['name' => 'Criuleni'],
    38 => ['name' => 'Dubăsari'],
    39 => ['name' => 'Orhei'],
    40 => ['name' => 'Soroca'],
    41 => ['name' => 'Bălți'],
    42 => ['name' => 'Florești'],
    43 => ['name' => 'Drochia'],
    44 => ['name' => 'Rîbnița'],
    45 => ['name' => 'Bender'],
    46 => ['name' => 'Tiraspol'],
    47 => ['name' => 'Cahul'],
    48 => ['name' => 'Comrat'],
    49 => ['name' => 'Vulcănești'],
    50 => ['name' => 'Ceadîr-Lunga'],
    51 => ['name' => 'Taraclia'],
    52 => ['name' => 'Basarabeasca'],
    53 => ['name' => 'Cimișlia'],
    54 => ['name' => 'Leova'],
    55 => ['name' => 'Hîncești'],
    56 => ['name' => 'Nisporeni'],
    57 => ['name' => 'Ungheni'],
    58 => ['name' => 'Strășeni'],
    59 => ['name' => 'Călărași'],
    60 => ['name' => 'Orhei'],
];
