<?php

return [
    1 => ['name' => 'Valletta'],
    2 => ['name' => 'Birkirkara'],
    3 => ['name' => 'Mosta'],
    4 => ['name' => 'Qormi'],
    5 => ['name' => 'Żabbar'],
    6 => ['name' => 'San Pawl il-Baħar'],
    7 => ['name' => 'Naxxar'],
    8 => ['name' => 'Sliema'],
    9 => ['name' => 'Żebbuġ'],
    10 => ['name' => 'Żejtun'],
    11 => ['name' => 'Attard'],
    12 => ['name' => 'Pembroke'],
    13 => ['name' => 'Marsaskala'],
    14 => ['name' => 'Paola'],
    15 => ['name' => 'Tarxien'],
    16 => ['name' => 'Fgura'],
    17 => ['name' => 'Żurrieq'],
    18 => ['name' => 'Santa Venera'],
    19 => ['name' => 'Msida'],
    20 => ['name' => 'San Ġwann'],
    21 => ['name' => 'Mellieħa'],
    22 => ['name' => 'St. Julian\'s'],
    23 => ['name' => 'Gżira'],
    24 => ['name' => 'Swieqi'],
    25 => ['name' => 'Marsa'],
    26 => ['name' => 'Kirkop'],
    27 => ['name' => 'Luqa'],
    28 => ['name' => 'Ħamrun'],
    29 => ['name' => 'Birżebbuġa'],
    30 => ['name' => 'Mdina'],
    31 => ['name' => 'Rabat'],
    32 => ['name' => 'Mqabba'],
    33 => ['name' => 'Qrendi'],
    34 => ['name' => 'Siġġiewi'],
    35 => ['name' => 'Żebbuġ Gozo'],
    36 => ['name' => 'Victoria'],
    37 => ['name' => 'Xewkija'],
    38 => ['name' => 'Nadur'],
    39 => ['name' => 'Xagħra'],
    40 => ['name' => 'Marsalforn'],
    41 => ['name' => 'Għajnsielem'],
    42 => ['name' => 'Qala'],
    43 => ['name' => 'Kerċem'],
    44 => ['name' => 'Fontana'],
    45 => ['name' => 'Għarb'],
    46 => ['name' => 'Għasri'],
    47 => ['name' => 'Munxar'],
    48 => ['name' => 'San Lawrenz'],
    49 => ['name' => 'Sannat'],
    50 => ['name' => 'Ta\' Sannat'],
    51 => ['name' => 'Xlendi'],
    52 => ['name' => 'Balzan'],
    53 => ['name' => 'Dingli'],
    54 => ['name' => 'Gudja'],
    55 => ['name' => 'Iklin'],
    56 => ['name' => 'Kalkara'],
    57 => ['name' => 'Lija'],
    58 => ['name' => 'Marsaxlokk'],
    59 => ['name' => 'Mtarfa'],
    60 => ['name' => 'Senglea'],
];
