<?php

return [
    1 => ['name' => 'Amsterdam'],
    2 => ['name' => 'Rotterdam'],
    3 => ['name' => 'The Hague'],
    4 => ['name' => 'Utrecht'],
    5 => ['name' => 'Eindhoven'],
    6 => ['name' => 'Groningen'],
    7 => ['name' => 'Tilburg'],
    8 => ['name' => 'Almere'],
    9 => ['name' => 'Breda'],
    10 => ['name' => 'Nijmegen'],
    11 => ['name' => 'Enschede'],
    12 => ['name' => 'Haarlem'],
    13 => ['name' => 'Arnhem'],
    14 => ['name' => 'Zaanstad'],
    15 => ['name' => 'Amersfoort'],
    16 => ['name' => 'Apeldoorn'],
    17 => ['name' => 'Den Bosch'],
    18 => ['name' => 'Hoofddorp'],
    19 => ['name' => 'Maastricht'],
    20 => ['name' => 'Leiden'],
    21 => ['name' => 'Dordrecht'],
    22 => ['name' => 'Zoetermeer'],
    23 => ['name' => 'Zwolle'],
    24 => ['name' => 'Deventer'],
    25 => ['name' => 'Ede'],
    26 => ['name' => 'Westland'],
    27 => ['name' => 'Venlo'],
    28 => ['name' => 'Leeuwarden'],
    29 => ['name' => 'Heerlen'],
    30 => ['name' => 'Hengelo'],
    31 => ['name' => 'Delft'],
    32 => ['name' => 'Oss'],
    33 => ['name' => 'Schiedam'],
    34 => ['name' => 'Purmerend'],
    35 => ['name' => 'Hilversum'],
    36 => ['name' => 'Spijkenisse'],
    37 => ['name' => 'Vlaardingen'],
    38 => ['name' => 'Gouda'],
    39 => ['name' => 'Alphen aan den Rijn'],
    40 => ['name' => 'Bergen op Zoom'],
    41 => ['name' => 'Hoorn'],
    42 => ['name' => 'Leidschendam-Voorburg'],
    43 => ['name' => 'Alkmaar'],
    44 => ['name' => 'Heerhugowaard'],
    45 => ['name' => 'Lelystad'],
    46 => ['name' => 'Helmond'],
    47 => ['name' => 'Emmen'],
    48 => ['name' => 'Assen'],
    49 => ['name' => 'Roosendaal'],
    50 => ['name' => 'Oosterhout'],
    51 => ['name' => 'Hoogeveen'],
    52 => ['name' => 'Kampen'],
    53 => ['name' => 'Sittard-Geleen'],
    54 => ['name' => 'Venray'],
    55 => ['name' => 'Weert'],
    56 => ['name' => 'Heerenveen'],
    57 => ['name' => 'Zaanstad'],
    58 => ['name' => 'Amstelveen'],
    59 => ['name' => 'Capelle aan den IJssel'],
    60 => ['name' => 'Haarlemmermeer'],
];
