<?php

return [
    1 => ['name' => 'Lisbon'],
    2 => ['name' => 'Porto'],
    3 => ['name' => 'Amadora'],
    4 => ['name' => 'Braga'],
    5 => ['name' => 'Coimbra'],
    6 => ['name' => 'Funchal'],
    7 => ['name' => 'Setúbal'],
    8 => ['name' => 'Almada'],
    9 => ['name' => 'Agualva-Cacém'],
    10 => ['name' => 'Queluz'],
    11 => ['name' => 'Faro'],
    12 => ['name' => 'Vila Nova de Gaia'],
    13 => ['name' => 'Gondomar'],
    14 => ['name' => 'Guimarães'],
    15 => ['name' => 'Odivelas'],
    16 => ['name' => 'Matosinhos'],
    17 => ['name' => 'Amora'],
    18 => ['name' => 'Barreiro'],
    19 => ['name' => 'Évora'],
    20 => ['name' => 'Portimão'],
    21 => ['name' => 'Aveiro'],
    22 => ['name' => 'Leiria'],
    23 => ['name' => 'Ponta Delgada'],
    24 => ['name' => 'Fafe'],
    25 => ['name' => 'Viseu'],
    26 => ['name' => 'Covilhã'],
    27 => ['name' => 'Castelo Branco'],
    28 => ['name' => 'Santarém'],
    29 => ['name' => 'Beja'],
    30 => ['name' => 'Portalegre'],
    31 => ['name' => 'Lagos'],
    32 => ['name' => 'Tavira'],
    33 => ['name' => 'Olhão'],
    34 => ['name' => 'Loulé'],
    35 => ['name' => 'Silves'],
    36 => ['name' => 'Albufeira'],
    37 => ['name' => 'Faro'],
    38 => ['name' => 'Lamego'],
    39 => ['name' => 'Chaves'],
    40 => ['name' => 'Vila Real'],
    41 => ['name' => 'Bragança'],
    42 => ['name' => 'Figueira da Foz'],
    43 => ['name' => 'Pombal'],
    44 => ['name' => 'Tomar'],
    45 => ['name' => 'Torres Vedras'],
    46 => ['name' => 'Caldas da Rainha'],
    47 => ['name' => 'Sintra'],
    48 => ['name' => 'Cascais'],
    49 => ['name' => 'Oeiras'],
    50 => ['name' => 'Loures'],
    51 => ['name' => 'Ovar'],
    52 => ['name' => 'Espinho'],
    53 => ['name' => 'Viana do Castelo'],
    54 => ['name' => 'Póvoa de Varzim'],
    55 => ['name' => 'Maia'],
    56 => ['name' => 'Vila do Conde'],
    57 => ['name' => 'Paredes'],
    58 => ['name' => 'Felgueiras'],
    59 => ['name' => 'Vizela'],
    60 => ['name' => 'Barcelos'],
];
