<?php

return [
    1 => ['name' => 'Bucharest'],
    2 => ['name' => 'Cluj-Napoca'],
    3 => ['name' => 'Timișoara'],
    4 => ['name' => 'Iași'],
    5 => ['name' => 'Constanța'],
    6 => ['name' => 'Craiova'],
    7 => ['name' => 'Brașov'],
    8 => ['name' => 'Galați'],
    9 => ['name' => 'Ploiești'],
    10 => ['name' => 'Oradea'],
    11 => ['name' => 'Brăila'],
    12 => ['name' => 'Arad'],
    13 => ['name' => 'Pitești'],
    14 => ['name' => 'Sibiu'],
    15 => ['name' => 'Bacău'],
    16 => ['name' => 'Târgu Mureș'],
    17 => ['name' => 'Baia Mare'],
    18 => ['name' => 'Buzău'],
    19 => ['name' => 'Satu Mare'],
    20 => ['name' => 'Botoșani'],
    21 => ['name' => 'Râmnicu Vâlcea'],
    22 => ['name' => 'Suceava'],
    23 => ['name' => 'Piatra Neamț'],
    24 => ['name' => 'Drobeta-Turnu Severin'],
    25 => ['name' => 'Focșani'],
    26 => ['name' => 'Târgu Jiu'],
    27 => ['name' => 'Târgu Secuiesc'],
    28 => ['name' => 'Reșița'],
    29 => ['name' => 'Bistrița'],
    30 => ['name' => 'Slatina'],
    31 => ['name' => 'Călărași'],
    32 => ['name' => 'Alba Iulia'],
    33 => ['name' => 'Giurgiu'],
    34 => ['name' => 'Deva'],
    35 => ['name' => 'Zalău'],
    36 => ['name' => 'Sfântu Gheorghe'],
    37 => ['name' => 'Turda'],
    38 => ['name' => 'Mediaș'],
    39 => ['name' => 'Slobozia'],
    40 => ['name' => 'Onești'],
    41 => ['name' => 'Alexandria'],
    42 => ['name' => 'Lugoj'],
    43 => ['name' => 'Medgidia'],
    44 => ['name' => 'Popești-Leordeni'],
    45 => ['name' => 'Voluntari'],
    46 => ['name' => 'Sighișoara'],
    47 => ['name' => 'Mangalia'],
    48 => ['name' => 'Sinaia'],
    49 => ['name' => 'Bârlad'],
    50 => ['name' => 'Vaslui'],
    51 => ['name' => 'Tecuci'],
    52 => ['name' => 'Pașcani'],
    53 => ['name' => 'Petroșani'],
    54 => ['name' => 'Lupeni'],
    55 => ['name' => 'Băilești'],
    56 => ['name' => 'Făgăraș'],
    57 => ['name' => 'Sighetu Marmației'],
    58 => ['name' => 'Târnăveni'],
    59 => ['name' => 'Câmpina'],
    60 => ['name' => 'Băicoi'],
];
