<?php

return [
    1 => ['name' => 'Moscow'],
    2 => ['name' => 'Saint Petersburg'],
    3 => ['name' => 'Novosibirsk'],
    4 => ['name' => 'Yekaterinburg'],
    5 => ['name' => 'Kazan'],
    6 => ['name' => 'Nizhny Novgorod'],
    7 => ['name' => 'Chelyabinsk'],
    8 => ['name' => 'Samara'],
    9 => ['name' => 'Rostov-on-Don'],
    10 => ['name' => 'Ufa'],
    11 => ['name' => 'Krasnoyarsk'],
    12 => ['name' => 'Voronezh'],
    13 => ['name' => 'Perm'],
    14 => ['name' => 'Volgograd'],
    15 => ['name' => 'Krasnodar'],
    16 => ['name' => 'Saratov'],
    17 => ['name' => 'Tyumen'],
    18 => ['name' => 'Tolyatti'],
    19 => ['name' => 'Izhevsk'],
    20 => ['name' => 'Barnaul'],
    21 => ['name' => 'Ulyanovsk'],
    22 => ['name' => 'Irkutsk'],
    23 => ['name' => 'Khabarovsk'],
    24 => ['name' => 'Yaroslavl'],
    25 => ['name' => 'Vladivostok'],
    26 => ['name' => 'Makhachkala'],
    27 => ['name' => 'Tomsk'],
    28 => ['name' => 'Orenburg'],
    29 => ['name' => 'Kemerovo'],
    30 => ['name' => 'Novokuznetsk'],
    31 => ['name' => 'Ryazan'],
    32 => ['name' => 'Astrakhan'],
    33 => ['name' => 'Naberezhnye Chelny'],
    34 => ['name' => 'Penza'],
    35 => ['name' => 'Lipetsk'],
    36 => ['name' => 'Tula'],
    37 => ['name' => 'Kirov'],
    38 => ['name' => 'Cheboksary'],
    39 => ['name' => 'Kaliningrad'],
    40 => ['name' => 'Bryansk'],
    41 => ['name' => 'Kursk'],
    42 => ['name' => 'Ivanovo'],
    43 => ['name' => 'Magnitogorsk'],
    44 => ['name' => 'Tver'],
    45 => ['name' => 'Stavropol'],
    46 => ['name' => 'Sochi'],
    47 => ['name' => 'Vladikavkaz'],
    48 => ['name' => 'Murmansk'],
    49 => ['name' => 'Arkhangelsk'],
    50 => ['name' => 'Cherepovets'],
    51 => ['name' => 'Volzhsky'],
    52 => ['name' => 'Smolensk'],
    53 => ['name' => 'Kurgan'],
    54 => ['name' => 'Vladimir'],
    55 => ['name' => 'Chita'],
    56 => ['name' => 'Saransk'],
    57 => ['name' => 'Tambov'],
    58 => ['name' => 'Yoshkar-Ola'],
    59 => ['name' => 'Grozny'],
    60 => ['name' => 'Kostroma'],
];
