<?php

return [
    1 => ['name' => 'Ljubljana'],
    2 => ['name' => 'Maribor'],
    3 => ['name' => 'Celje'],
    4 => ['name' => 'Kranj'],
    5 => ['name' => 'Velenje'],
    6 => ['name' => 'Koper'],
    7 => ['name' => 'Novo Mesto'],
    8 => ['name' => 'Ptuj'],
    9 => ['name' => 'Trbovlje'],
    10 => ['name' => 'Kamnik'],
    11 => ['name' => 'Jesenice'],
    12 => ['name' => 'Nova Gorica'],
    13 => ['name' => 'Domžale'],
    14 => ['name' => 'Škofja Loka'],
    15 => ['name' => 'Murska Sobota'],
    16 => ['name' => 'Izola'],
    17 => ['name' => 'Kočevje'],
    18 => ['name' => 'Postojna'],
    19 => ['name' => 'Logatec'],
    20 => ['name' => 'Slovenj Gradec'],
    21 => ['name' => 'Ravne na Koroškem'],
    22 => ['name' => 'Vrhnika'],
    23 => ['name' => 'Krško'],
    24 => ['name' => 'Zagorje ob Savi'],
    25 => ['name' => 'Ajdovščina'],
    26 => ['name' => 'Brežice'],
    27 => ['name' => 'Črnomelj'],
    28 => ['name' => 'Dravograd'],
    29 => ['name' => 'Gornja Radgona'],
    30 => ['name' => 'Grosuplje'],
    31 => ['name' => 'Hrastnik'],
    32 => ['name' => 'Idrija'],
    33 => ['name' => 'Ilirska Bistrica'],
    34 => ['name' => 'Lendava'],
    35 => ['name' => 'Litija'],
    36 => ['name' => 'Ljubljana'],
    37 => ['name' => 'Ljutomer'],
    38 => ['name' => 'Metlika'],
    39 => ['name' => 'Mežica'],
    40 => ['name' => 'Mozirje'],
    41 => ['name' => 'Piran'],
    42 => ['name' => 'Pivka'],
    43 => ['name' => 'Prevalje'],
    44 => ['name' => 'Radlje ob Dravi'],
    45 => ['name' => 'Ravne'],
    46 => ['name' => 'Ribnica'],
    47 => ['name' => 'Rogatec'],
    48 => ['name' => 'Ruše'],
    49 => ['name' => 'Sevnica'],
    50 => ['name' => 'Sežana'],
    51 => ['name' => 'Slovenska Bistrica'],
    52 => ['name' => 'Slovenske Konjice'],
    53 => ['name' => 'Šentjur'],
    54 => ['name' => 'Šmarje pri Jelšah'],
    55 => ['name' => 'Tolmin'],
    56 => ['name' => 'Tržič'],
    57 => ['name' => 'Turnišče'],
    58 => ['name' => 'Vipava'],
    59 => ['name' => 'Žalec'],
    60 => ['name' => 'Železniki'],
];
