<?php

return [
    1 => ['name' => 'Bratislava', 'region' => 'Bratislavský kraj'],
    2 => ['name' => 'Košice', 'region' => 'Košický kraj'],
    3 => ['name' => 'Prešov', 'region' => 'Prešovský kraj'],
    4 => ['name' => 'Žilina', 'region' => 'Žilinský kraj'],
    5 => ['name' => 'Nitra', 'region' => 'Nitriansky kraj'],
    6 => ['name' => 'Banská Bystrica', 'region' => 'Banskobystrický kraj'],
    7 => ['name' => 'Trnava', 'region' => 'Trnavský kraj'],
    8 => ['name' => 'Martin', 'region' => 'Žilinský kraj'],
    9 => ['name' => 'Trenčín', 'region' => 'Trenčiansky kraj'],
    10 => ['name' => 'Poprad', 'region' => 'Prešovský kraj'],
    11 => ['name' => 'Prievidza'],
    12 => ['name' => 'Zvolen'],
    13 => ['name' => 'Považská Bystrica'],
    14 => ['name' => 'Nové Zámky'],
    15 => ['name' => 'Michalovce'],
    16 => ['name' => 'Spišská Nová Ves'],
    17 => ['name' => 'Komárno'],
    18 => ['name' => 'Humenné'],
    19 => ['name' => 'Levice'],
    20 => ['name' => 'Bardejov'],
    21 => ['name' => 'Liptovský Mikuláš'],
    22 => ['name' => 'Lučenec'],
    23 => ['name' => 'Piešťany'],
    24 => ['name' => 'Ružomberok'],
    25 => ['name' => 'Topoľčany'],
    26 => ['name' => 'Trebišov'],
    27 => ['name' => 'Čadca'],
    28 => ['name' => 'Rimavská Sobota'],
    29 => ['name' => 'Dunajská Streda'],
    30 => ['name' => 'Pezinok'],
    31 => ['name' => 'Šaľa'],
    32 => ['name' => 'Partizánske'],
    33 => ['name' => 'Vranov nad Topľou'],
    34 => ['name' => 'Hlohovec'],
    35 => ['name' => 'Brezno'],
    36 => ['name' => 'Snina'],
    37 => ['name' => 'Senica'],
    38 => ['name' => 'Nové Mesto nad Váhom'],
    39 => ['name' => 'Kežmarok'],
    40 => ['name' => 'Rožňava'],
    41 => ['name' => 'Dolný Kubín'],
    42 => ['name' => 'Bánovce nad Bebravou'],
    43 => ['name' => 'Púchov'],
    44 => ['name' => 'Malacky'],
    45 => ['name' => 'Handlová'],
    46 => ['name' => 'Kysucké Nové Mesto'],
    47 => ['name' => 'Galanta'],
    48 => ['name' => 'Stará Ľubovňa'],
    49 => ['name' => 'Žiar nad Hronom'],
    50 => ['name' => 'Skalica'],
    51 => ['name' => 'Senec'],
    52 => ['name' => 'Stropkov'],
    53 => ['name' => 'Šamorín'],
    54 => ['name' => 'Stará Turá'],
    55 => ['name' => 'Fiľakovo'],
    56 => ['name' => 'Svidník'],
    57 => ['name' => 'Šurany'],
    58 => ['name' => 'Tvrdošín'],
    59 => ['name' => 'Veľký Krtíš'],
    60 => ['name' => 'Myjava'],
];
