<?php

return [
    1 => ['name' => 'Ashgabat'],
    2 => ['name' => 'Türkmenabat'],
    3 => ['name' => 'Daşoguz'],
    4 => ['name' => 'Mary'],
    5 => ['name' => 'Balkanabat'],
    6 => ['name' => 'Balkanabat'],
    7 => ['name' => 'Tejen'],
    8 => ['name' => 'Bayramaly'],
    9 => ['name' => 'Türkmenbashi'],
    10 => ['name' => 'Abadan'],
    11 => ['name' => 'Yolöten'],
    12 => ['name' => 'Köneürgenç'],
    13 => ['name' => 'Anau'],
    14 => ['name' => 'Büzmeýin'],
    15 => ['name' => 'Gumdag'],
    16 => ['name' => 'Gazanjyk'],
    17 => ['name' => 'Bereket'],
    18 => ['name' => 'Serdar'],
    19 => ['name' => 'Gökdepe'],
    20 => ['name' => 'Kaka'],
    21 => ['name' => 'Seydi'],
    22 => ['name' => 'Atamyrat'],
    23 => ['name' => 'Farap'],
    24 => ['name' => 'Garabogaz'],
    25 => ['name' => 'Gowurdak'],
    26 => ['name' => 'Gyzylarbat'],
    27 => ['name' => 'Hazar'],
    28 => ['name' => 'Köneürgenç'],
    29 => ['name' => 'Magdanly'],
    30 => ['name' => 'Sakarçäge'],
    31 => ['name' => 'Serhetabat'],
    32 => ['name' => 'Tagta'],
    33 => ['name' => 'Türkmenabat'],
    34 => ['name' => 'Yylgyndere'],
    35 => ['name' => 'Akdepe'],
    36 => ['name' => 'Boldumsaz'],
    37 => ['name' => 'Gurbansoltan eje'],
    38 => ['name' => 'Görogly'],
    39 => ['name' => 'Gubadag'],
    40 => ['name' => 'Köneürgenç'],
    41 => ['name' => 'Saparmyrat Türkmenbaşy'],
    42 => ['name' => 'Tagta'],
    43 => ['name' => 'Tejen'],
    44 => ['name' => 'Sarahs'],
    45 => ['name' => 'Murgap'],
    46 => ['name' => 'Sakarchaga'],
    47 => ['name' => 'Kerki'],
    48 => ['name' => 'Halaç'],
    49 => ['name' => 'Dostluk'],
    50 => ['name' => 'Gumdag'],
    51 => ['name' => 'Hazar'],
    52 => ['name' => 'Çeleken'],
    53 => ['name' => 'Garabogaz'],
    54 => ['name' => 'Balkanabat'],
    55 => ['name' => 'Etrek'],
    56 => ['name' => 'Gyzyletrek'],
    57 => ['name' => 'Serdar'],
    58 => ['name' => 'Bereket'],
    59 => ['name' => 'Magtymguly'],
    60 => ['name' => 'Türkmenbashi'],
];
